---
language: ruby
rvm:
  - 2.6.3

services:
  - docker

env:
  global:
    - ROLE_NAME: lotus

before_script:
  - sudo pip install ansible-lint yamllint

script:
  - ansible-lint -x 403 -c ./test/lint/.ansible-lint .
  - yamllint --config-file ./test/lint/yaml-lint.yml .
  - bundle exec kitchen test service-launch-ubuntu-1804
  - bundle exec kitchen test service-launch-centos-7

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
