---
- name: Check for uninstall signal
  command: /bin/true
  notify: Uninstall Lotus
  when: perform_uninstall

- name: End play following uninstallation
  meta: end_play
  when: perform_uninstall

- name: Include OS and distribution specific variables.
  include_vars: "{{ item }}"
  with_first_found:
    - files:
        - "{{ ansible_distribution|lower }}.yml"
        - "{{ ansible_os_family|lower }}.yml"
      skip: true
  tags:
    - always

- name: Include OS and distribution specific installation tasks.
  include_tasks: "{{ item }}"
  with_first_found:
    - files:
        - "{{ ansible_distribution|lower }}/install.yml"
        - "{{ ansible_os_family|lower }}/install.yml"
      skip: true
  tags:
    - install

- name: Include common preflight tasks
  include_tasks: "common/preflight.yml"
  tags:
    - preflight

- name: Include common installation tasks
  include_tasks: "common/install.yml"
  tags:
    - install

- name: Include common configuration tasks
  include_tasks: "common/config.yml"
  tags:
    - config

- name: Include common launch tasks
  include_tasks: "common/launch.yml"
  tags:
    - launch
