---
- name: Restart lotus service
  become: true
  service:
    name: lotus
    state: restarted
  listen: Restart service
  when: not perform_uninstall

- name: Remove lotus install dir
  become: true
  file:
    path: "{{ install_dir }}"
    state: absent
  listen: Uninstall Lotus

- name: Remove lotus path dir
  file:
    path: "{{ lotus_path }}"
    state: absent
  become: true
  listen: Uninstall Lotus

- name: Remove lotus storage path dir
  file:
    path: "{{ lotus_storage_path }}"
    state: absent
  become: true
  listen: Uninstall Lotus

- name: Stop lotus systemd service
  service:
    name: lotus
    state: stopped
    enabled: false
  listen: Uninstall Lotus

- name: Remove Lotus systemd service file
  become: true
  file:
    path: "/etc/systemd/system/lotus.service"
    state: absent
  listen: Uninstall Lotus
  when: ansible_os_family|lower != 'darwin'

- name: Remove lotus user
  user:
    name: "{{ lotus_user }}"
    state: absent
    remove: true
  listen: Uninstall Lotus

- name: Remove lotus group
  group:
    name: "{{ lotus_user }}"
    state: absent
  listen: Uninstall Lotus
