---
#######  Source installation #######

- name: Update and upgrade apt packages
  become: true
  apt:
    upgrade: 'yes'
    update_cache: 'yes'

- name: Download and extract Go-lang
  become: true
  unarchive:
    src: "{{ go_url }}"
    dest: "{{ go_install_dir }}"
    mode: '0775'
    remote_src: 'yes'

- name: Create a symbolic link to /usr/local/bin/go
  become: true
  file:
    src: "{{ go_install_dir }}/go/bin/go"
    dest: /usr/local/bin/go
    state: link

- name: Update and upgrade apt packages
  become: true
  apt:
    upgrade: 'yes'

- name: update dependencies
  become: true
  package:
    name: "{{ item }}"
    state: present
  loop: "{{ system_dependencies }}"
