---
- name: Ensure existence of config dir
  become: true
  file:
    path: "{{ lotus_path }}"
    owner: "{{ lotus_user }}"
    group: "{{ lotus_user }}"
    state: directory

- name: Render Lotus configuration
  become: true
  template:
    src: "{{ _lotus_config_file }}.j2"
    dest: "{{ lotus_path }}/{{ _lotus_config_file }}"
    owner: "{{ lotus_user }}"
    group: "{{ lotus_user }}"
    mode: 0644
  vars:
    conf: "{{ config }}"
  when: config is defined and config is not none

- name: Ensure existence of Lotus storage path
  become: true
  file:
    path: "{{ lotus_storage_path }}"
    owner: "{{ lotus_user }}"
    group: "{{ lotus_user }}"
    state: directory
