---
#######  Authentication setup #######

- name: Ensure Lotus group exists
  group:
    name: "{{ lotus_user }}"
    state: present
  become: true

- name: Create Lotus user
  user:
    comment: Lotus service account
    name: "{{ lotus_user }}"
    group: "{{ lotus_user }}"
    create_home: "no"
  become: true

#######  Source installation #######

- name: Create installation directory
  become: true
  file:
    path: "{{ install_dir }}"
    state: directory

- name: Clone lotus git repository
  become: true
  git:
    repo: "{{ git_url }}"
    dest: "{{ install_dir }}"
    version: "v0.1.0"

- name: Reset state of source
  become: true
  make:
    chdir: "{{ install_dir }}"
    target: clean
  environment:
    PATH: /usr/local/bin:{{ ansible_env.PATH }}

- name: Build source package
  become: true
  make:
    chdir: "{{ install_dir }}"
    target: all
  environment:
    PATH: /usr/local/bin:{{ ansible_env.PATH }}

- name: Install lotus client and miner software
  become: true
  make:
    chdir: "{{ install_dir }}"
    target: install
  environment:
    PATH: /usr/local/bin:{{ ansible_env.PATH }}
