---
- name: Ensure Lotus group exists
  group:
    name: "{{ lotus_user }}"
    state: present
  become: true

- name: Create Lotus user
  user:
    comment: Lotus service account
    name: "{{ lotus_user }}"
    group: "{{ lotus_user }}"
  become: true

- name: Ensure existence of install dir
  become: true
  file:
    path: "{{ install_dir }}"
    owner: "{{ lotus_user }}"
    group: "{{ lotus_user }}"
    state: directory

- name: perform designated installation procedure
  include_tasks: "common/install/{{ install_type }}_install.yml"
