---
- name: Ensure Lotus group exists
  become: true
  group:
    name: "{{ lotus_user }}"
    state: present
    system: true
  tags:
    - install

- name: Create Lotus user
  become: true
  user:
    comment: Lotus service account
    name: "{{ lotus_user }}"
    group: "{{ lotus_user }}"
    shell: "/sbin/nologin"
    system: true
    create_home: false
  tags:
    - install

- name: Ensure existence of install dir
  become: true
  file:
    path: "{{ install_dir }}"
    owner: "{{ lotus_user }}"
    group: "{{ lotus_user }}"
    state: directory
  tags:
    - install

- name: perform designated installation procedure
  include_tasks: "common/install/{{ install_type }}_install.yml"
  tags:
    - install
