---
- name: Ensure Lotus group exists
  become: true
  group:
    name: "{{ lotus_user }}"
    state: present
    system: true

- name: Create Lotus user
  become: true
  user:
    comment: Lotus service account
    name: "{{ lotus_user }}"
    group: "{{ lotus_user }}"
    shell: "/sbin/nologin"
    system: true
    create_home: false

- name: Ensure existence of install dir
  become: true
  file:
    path: "{{ install_dir }}"
    owner: "{{ lotus_user }}"
    group: "{{ lotus_user }}"
    state: directory

- name: perform designated installation procedure
  include_tasks: "common/install/{{ install_type }}_install.yml"
