---
- name: Include OS and distribution specific variables.
  include_vars: "{{ item }}"
  with_first_found:
    - files:
        - "{{ ansible_distribution|lower }}.yml"
        - "{{ ansible_os_family|lower }}.yml"
      skip: true
  tags:
    - always

- name: Check for uninstall signal
  when: perform_uninstall
  block:
    - name: Broadcast uninstall signal
      command: /bin/true
      notify: Uninstall Lotus
      when: perform_uninstall

    - name: End play following uninstallation
      meta: end_play
  tags:
    - always

- name: Update system packages
  become: true
  when: go_autoinstall and ansible_os_family|lower == "redhat"
  yum:
    name: "*"
    state: latest
  tags:
    - preflight

- name: Add Go-lang backports repository to sources list
  become: true
  when: go_autoinstall and ansible_distribution|lower == "ubuntu"
  apt_repository:
    repo: ppa:longsleep/golang-backports
  tags:
    - preflight

- name: Update apt packages
  become: true
  when: go_autoinstall and ansible_os_family|lower == "debian"
  apt:
    upgrade: 'yes'
    update_cache: 'yes'
  tags:
    - preflight

- name: Download and extract Go-lang
  become: true
  when: go_autoinstall and ansible_distribution|lower != "ubuntu"
  unarchive:
    src: "{{ go_url }}"
    dest: "{{ go_install_dir }}"
    mode: '0775'
    remote_src: 'yes'
  tags:
    - preflight

- name: Update system dependencies
  become: true
  when: ansible_distribution|lower != "ubuntu"
  package:
    name: "{{ system_dependencies }}"
    state: present
  tags:
    - preflight

- name: Create a symbolic link to /usr/local/bin/go
  become: true
  when: go_autoinstall and ansible_distribution|lower != "Ubuntu"
  file:
    src: "{{ go_install_dir }}/go"
    dest: /usr/local/bin/go
    state: link
  tags:
    - preflight

- name: Set lotus service unit [Service] configuration
  set_fact:
    _default_service_unit:
      ExecStart: "/usr/local/bin/lotus daemon {{ extra_run_args|join(' ') }}"
      User: "{{ lotus_user }}"
      Group: "{{ lotus_user }}"
      StandardOutput: journal
      StandardError: inherit
      Environment: "LOTUS_PATH={{ lotus_path }} LOTUS_STORAGE_PATH={{ lotus_storage_path }}"
  tags:
    - preflight

- name: Set lotus miner unit [Service] configuration
  set_fact:
    _default_miner_unit:
      ExecStart: "/usr/local/bin/lotus-storage-miner run {{ extra_miner_args|join(' ') }}"
      User: "{{ lotus_user }}"
      Group: "{{ lotus_user }}"
      StandardOutput: journal
      StandardError: inherit
      Environment: "LOTUS_PATH={{ lotus_path }} LOTUS_STORAGE_PATH={{ lotus_storage_path }}"
  tags:
    - preflight
