---
- name: Include OS and distribution specific variables.
  include_vars: "{{ item }}"
  with_first_found:
    - files:
        - "{{ ansible_distribution|lower }}.yml"
        - "{{ ansible_os_family|lower }}.yml"
      skip: true
  tags:
    - always

- name: Check for uninstall signal
  when: perform_uninstall
  block:
    - name: Broadcast uninstall signal
      command: /bin/true
      notify:
        - Uninstall service
  always:
    - name: Ensure flush of handlers
      meta: flush_handlers
    - name: End play following uninstallation
      meta: end_play
  tags:
    - preflight

- name: Download and extract Go-lang
  become: true
  when: go_autoinstall
  unarchive:
    src: "{{ go_url }}"
    dest: "{{ go_install_dir }}"
    mode: '0775'
    remote_src: 'yes'
  tags:
    - preflight

- name: Update system dependencies
  become: true
  package:
    name: "{{ system_dependencies }}"
    state: present
  tags:
    - preflight

- name: Create a symbolic link to installed go binary
  become: true
  when: go_autoinstall
  file:
    src: "{{ go_install_dir }}/go/bin/go"
    dest: /usr/local/bin/go
    state: link
  tags:
    - preflight

- name: Set lotus service unit [Service] configuration
  set_fact:
    _default_service_unit:
      ExecStart: "/usr/local/bin/lotus daemon {{ extra_run_args|join(' ') }}"
      User: "{{ lotus_user }}"
      Group: "{{ lotus_user }}"
      StandardOutput: journal
      StandardError: inherit
      Environment: "LOTUS_PATH={{ lotus_path }} LOTUS_STORAGE_PATH={{ lotus_storage_path }}"
  tags:
    - preflight

- name: Set lotus miner unit [Service] configuration
  set_fact:
    _default_miner_unit:
      ExecStart: "/usr/local/bin/lotus-storage-miner run {{ extra_miner_args|join(' ') }}"
      User: "{{ lotus_user }}"
      Group: "{{ lotus_user }}"
      StandardOutput: journal
      StandardError: inherit
      Environment: "LOTUS_PATH={{ lotus_path }} LOTUS_STORAGE_PATH={{ lotus_storage_path }}"
  tags:
    - preflight
