---
- name: Download Lotus archive ({{ archive_url }})
  get_url:
    url: "{{ archive_url }}"
    dest: "/tmp/{{ archive_url | urlsplit('path') | basename }}"
    checksum: "{{ checksum_format }}:{{ archive_checksum }}"
    mode: '0775'
  register: archive_tmp
  become: true
  when: install_type == "archive"
  tags:
    - install
    - archive

- name: Extract Lotus archive
  unarchive:
    src: "{{ archive_tmp.dest }}"
    dest: "{{ install_dir }}"
    mode: '0775'
    owner: "{{ lotus_user }}"
    group: "{{ lotus_user }}"
    extra_opts:
      - --strip-components
      - '1'
    remote_src: true
  become: true
  when: install_type == "archive"
  notify:
    - Restart service
  tags:
    - install
    - archive

- name: Create a symbolic link to /usr/local/bin/lotus
  become: true
  file:
    src: "{{ install_dir }}/lotus"
    dest: /usr/local/bin/lotus
    state: link
  when: install_type == "archive"
  notify:
    - Restart service
  tags:
    - install
    - archive
